danielslist/config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "danielslist.herokuapp.com"
	root :to => 'session#new'

	get '/searches' => 'searches#results'
	
	resources :categories
	resources :subcategories
	resources :items

	get '/users/edit' => 'users#edit', :as => :edit_user
	resources :users, :except => [:edit]

 	get '/login' => 'session#new'
 	post '/login' => 'session#create'
 	delete '/login' => 'session#destroy'

 	get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  	get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  	get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  	resources :conversations do
    	member do
      		post :reply
      		post :trash
      		post :untrash
    	end
  	end
end

danielslist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Danielslist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Danielslist</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= categories_path %>">Category Index</a></li>
       	<li><a href="<%= new_item_path %>">Post</a></li>
    <% if @current_user.present? && @current_user.admin? %>
        <li><a href="<%= users_path %>">User Index</a></li>
    <% else %>

    <% end %>

      </ul>
    <%= form_tag searches_path, :method => 'get', :class => 'navbar-form navbar-left' do %>
		 	<div class="form-group">
		 	  <%= text_field_tag :search, params[:search], :class => 'form-control' %>
		 	</div>
		
		  <%= submit_tag "Search", :name => nil, :class => 'btn btn-default' %>  

		<% end %>

     


      <ul class="nav navbar-nav navbar-right">

        <% if @current_user.present? %>
        	<li class="active"><a href="<%= user_path(@current_user) %>"><%= @current_user.username %><span class="sr-only">(current)</span></a></li>

        	<li class="dropdown">
          		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Options<span class="caret"></span></a>
          		<ul class="dropdown-menu">
            		<li><a href="<%= edit_user_path(@current_user) %>">Edit Details</a></li>
            		<li><a href="<%= mailbox_inbox_path %>">Inbox</a></li>
            		<li><%= link_to 'Log out', login_path, :method => 'delete', :data => {:confirm => 'Are you sure you wish to log out?'} %></li>
          		</ul>
        	</li>
        <% else %>
        	<li class="active"><a href="<%= root_path %>">Sign In<span class="sr-only">(current)</span></a></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>











<div class="container">
	<% if flash[:message].present? %>
		<p><%= flash[:message] %></p>
	<% end %>

	

	<%= yield %>
</div>



</body>
</html>