danielslist/config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "danielslist.herokuapp.com"
	root :to => 'session#new'

	get '/searches' => 'searches#results'
	
	resources :categories
	resources :subcategories
	resources :items

	get '/users/edit' => 'users#edit', :as => :edit_user
	resources :users, :except => [:edit]

 	get '/login' => 'session#new'
 	post '/login' => 'session#create'
 	delete '/login' => 'session#destroy'

 	get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  	get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  	get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  	resources :conversations do
    	member do
      		post :reply
      		post :trash
      		post :untrash
    	end
  	end
end

danielslist/app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :check_if_logged_in
	before_action :conversation, :only => [:show]

	def new
    end

  def create
    # raise "why don't you load??"
    recipients = User.find_by(id: conversation_params[:recipients])
    conversation = @current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(@current_user)
    # mark conversation as read
    conversation.mark_as_read(@current_user)
  end

  def reply
    @current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def trash
      conversation.move_to_trash(@current_user)
      redirect_to mailbox_inbox_path
    end

    def untrash
      conversation.untrash(@current_user)
      redirect_to mailbox_inbox_path
    end

  private
  def check_if_logged_in
    redirect_to root_path unless @current_user.present?
  end

  def conversation_params
      params.require(:conversation).permit(:subject, :body, :recipients)
    end

    def message_params
      params.require(:message).permit(:body, :subject)
    end
end

danielslist/app/helpers/conversations_helper.rb
module ConversationsHelper
end

danielslist/app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="col-md-3 text-right">
    <% if conversation.is_trashed?(@current_user) %>
        <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                    data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.username %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
</div>

danielslist/app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
     To: <%= User.find(params[:recipient_id]).username %>
     <%= f.hidden_field :recipients, :value => params[:recipient_id] %>
    </div>
    <div class="form-group">
      Re: <%= params[:subject] %>
      <%= f.hidden_field :subject, :value => params[:subject] %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

danielslist/app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.username %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

danielslist/app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

danielslist/app/views/conversations/show.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div id="messagehistory" class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(@conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>