danielslist/config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "danielslist.herokuapp.com"
	root :to => 'session#new'

	get '/searches' => 'searches#results'
	
	resources :categories
	resources :subcategories
	resources :items

	get '/users/edit' => 'users#edit', :as => :edit_user
	resources :users, :except => [:edit]

 	get '/login' => 'session#new'
 	post '/login' => 'session#create'
 	delete '/login' => 'session#destroy'

 	get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  	get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  	get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  	resources :conversations do
    	member do
      		post :reply
      		post :trash
      		post :untrash
    	end
  	end
end

danielslist/app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id             :integer          not null, primary key
#  name           :string
#  description    :text
#  price          :float
#  image          :string
#  created_at     :datetime
#  updated_at     :datetime
#  subcategory_id :integer
#  user_id        :integer
#  category_id    :integer
#

class Item < ActiveRecord::Base
	belongs_to :subcategory
	belongs_to :user
	
	
	
	validates :name, :presence => true
	validates :description, :presence => true
	validates :price, :presence => true
	validates :category_id, :presence => true
	validates :subcategory_id, :presence => true
end

danielslist/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	@items = Item.all
  end

  def show
  	@item = Item.find params[:id]
  end

  def new
    @item = Item.new
  end

  def create
    params[:item][:price] = params["price"] || 0
  	@item = Item.create item_params
    if @item.category_id == 'personals' || @item.category_id == 'community'
      # if (params[:price] == nil)
      #   item_details = item_params
      #   item_details[:price] = '0'
      item = @current_user.items << @item
    
    end

  if (params[:file] == nil)
    item_details = item_params
    item_details[:image] = 'http://fillmurray.com/200/200'
    item = @current_user.items.create item_details

  else
    response = Cloudinary::Uploader.upload params[:file]
    item_details = item_params
    item_details[:image] = response["url"]
    item = @current_user.items.create item_details
    redirect_to item_path
  end

  if @item.save
    redirect_to item
  else
    render :new
  end
end

  def edit
  	@item = Item.find params[:id]
  end

  def update
  	item = Item.find params[:id]
  	item.update item_params
    redirect_to item_path
  end

  def destroy
  	item = Item.find params[:id]
  	item.destroy
  	redirect_to @current_user
  end

  private
  def item_params
      params.require(:item).permit(:name, :description, :price, :image, :subcategory_id, :category_id, :user_id)
      
  end


end

danielslist/app/helpers/items_helper.rb
module ItemsHelper
end

danielslist/app/views/items/_form.html.erb
<% if @current_user.present? %>
	<% if @item.errors.any? %>
		<ul>
			<% @item.errors.full_messages.each do |msg| %>
			<li>
				<%= msg %>
			</li>
			<% end %>
		</ul>
	<% end %>
	<%= form_for @item,:html => { :multipart => true } do |f| %>
	
	<div class="row">
		<div class="col-md-3"></div>
		<div class="form-group col-md-6">
			<%= f.label :category_id, 'Category' %>
			<%= f.select :category_id, Category.all.map{|category| ["#{category.name}", category.id]}, :include_blank => true %>
			<%= f.label :subcategory_id, 'Subcategory' %>
			<%= f.select :subcategory_id, Subcategory.all.map{|subcategory| ["#{subcategory.category.name}: #{subcategory.name}", subcategory.id]}, :include_blank => true %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3"></div>
		<div class="form-group col-md-6">
			<%= f.label :name, :class => 'sr-only', :for => 'exampleInputName3' %>
			<%= f.text_field :name, :class => 'form-control', :id => 'exampleInputName3', :placeholder => 'Item Name' %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3"></div>
		<div class="form-group col-md-6">
			<%= f.label :description, :class => 'sr-only', :for => 'exampleInputDescription3' %>
			<%= f.text_area :description, :class => 'form-control', :id => 'exampleInputDescription3', :placeholder => 'Description' %>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-3"></div>
		<div class="form-group col-md-6">
			<%= f.label :price, :class => 'sr-only', :for => 'exampleInputPrice3' %>
			<%= f.text_field :price, :class => 'form-control', :id => 'exampleInputPrice3', :placeholder => 'Price ($)' %>
		</div>
	</div>
	




	<div class="form-group">
		<div class="col-md-3"></div>
		<%= f.cl_image_upload :file %>
	</div>
	<div class="form-group">
		<div class="col-md-3"></div>
		<p><%= submit_tag "Post", :class => 'btn btn-default' %></p>
	</div>
	

	<% end %>
<% else %>

<p class="centre">You need to have an account to post an item.</p>
<p class="centre">Please <%= link_to 'Sign In', root_path %>, or <%= link_to 'Create an Account', new_user_path %>.</p>


<% end %>

danielslist/app/views/items/edit.html.erb
<div class="jumbotron">
	
	<h2 class="centre1">Edit Item</h2>

	<%= render :partial => 'form' %>

</div>

danielslist/app/views/items/index.html.erb
<div class="jumbotron">
	<h2>Item Index</h2>

	<ul>
		<% @items.each do |item| %>
		<li>
			<ul>
				<div class="col-md-3">

					<li>
						<%= item.name %>
					</li>
					<li>
						<%= link_to(cl_image_tag(item.image, :width=>200, :crop=>:thumb, :gravity=>:face, :effect=>"vibrance"), item) %>
					</li>
				</div>
			</ul>
		</li>
		<% end %>
	</ul>

</div>

danielslist/app/views/items/new.html.erb
<div class="jumbotron">
	<h2 class="centre1">New Item</h2>

	<%= render :partial => 'form' %>
</div>

danielslist/app/views/items/show.html.erb
<div class="jumbotron">
	<div class="centre">
		<h2><%= @item.name %></h2>
		<% if @item.subcategory.category.name == 'community' || @item.subcategory.category.name == 'personals' %>
			
		<% else %>
			<p><%= number_to_currency(@item.price) %></p>
		<% end %>


		<% if @item.image %>
			<p><%= cl_image_tag(@item.image, :width=>200, :crop=>:thumb, :gravity=>:face, :effect=>"vibrance") %></p> 
		<% end %>

		<p><%= @item.description %></p>

		<p><%= link_to(@item.subcategory.name, subcategory_path(@item.subcategory)) %></p>

		<p><%= link_to(@item.subcategory.category.name, category_path(@item.subcategory.category)) %></p>

		<p>Posted: <%= @item.created_at.strftime "%e %B, %Y" %></p>



		<% if (@current_user == @item.user) || (@current_user && @current_user.admin?) %>
		<p><%= link_to(@item.user.username, user_path) %></p>

		<div class="controls">
			<%= link_to 'Edit Item', edit_item_path(@item) %>
			<%= link_to 'Delete Item', @item, :method => 'delete', :data => {:confirm => "Are you sure you want to delete this item?"} %>
		</div>
		<% else %>
			<p>Contact: <%= link_to @item.user.username, new_conversation_path(:recipient_id => @item.user.id, :subject => @item.name) %></p>
		<% end %>
	</div>
	
</div>