danielslist/config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "danielslist.herokuapp.com"
	root :to => 'session#new'

	get '/searches' => 'searches#results'
	
	resources :categories
	resources :subcategories
	resources :items

	get '/users/edit' => 'users#edit', :as => :edit_user
	resources :users, :except => [:edit]

 	get '/login' => 'session#new'
 	post '/login' => 'session#create'
 	delete '/login' => 'session#destroy'

 	get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  	get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  	get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  	resources :conversations do
    	member do
      		post :reply
      		post :trash
      		post :untrash
    	end
  	end
end

danielslist/app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
	before_action :check_if_logged_in

	def inbox
    	@inbox = @current_user.mailbox.inbox
   		@active = :inbox
  	end

  	def sent
    	@sent = @current_user.mailbox.sentbox
    	@active = :sent
  	end

  	def trash
    	@trash = @current_user.mailbox.trash
    	@active = :trash
  	end

	def check_if_logged_in
  		redirect_to root_path unless @current_user.present?
 	end
end

danielslist/app/helpers/mailbox_helper.rb
module MailboxHelper
	def unread_messages_count
		# how to get the number of unread messages for the current user
    	# using mailboxer
    	@current_user.mailbox.inbox(:unread => true).count(:id, :distinct => true)
	end
end

danielslist/app/views/mailbox/_folder_view.html.erb
<div class="row">
  
  <div class="col-lg-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-lg-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <!-- individual conversations will show here -->
      </div>
    </div>
  </div>


  <div class="col-lg-8">
    <div class="panel panel-default">
      <div id="conversations" class="panel-body">
        <% if is_conversation %>
            <%= render 'conversations/form' %>
        <% else %>
            <%= render partial: 'conversations/conversation', collection: messages %>
        <% end %>
      </div>
    </div>
  </div>

</div>

danielslist/app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class="fa fa-inbox  fa-lg"></em>
        <span>Inbox</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>

        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span>Sent</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span>Trash</span>
    <% end %>
  </li>
</ul>

danielslist/app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

danielslist/app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

danielslist/app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>